apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 6
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.3.1
          name: mealie
          ports:
            - containerPort: 9000
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 2
